<?php

namespace Jmoati\Gitolite\ConsoleBundle\Command;

use Gitter\Client;
use Jmoati\HelperBundle\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class GenerateCommand extends Command
{

    protected function configure()
    {
        parent::configure();

        $this
            ->setName('jmoati:gitolite:generate')
            ->setDescription('Create config file with batabase data');
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        parent::execute($input, $output);

        $web_user = $this->getParameter('web_user');

        $process = $this->runProcess(
            'whoami',
            "<info>*</info> Are you {$web_user} or root? "
        );

        $username = trim($process->getOutput());

        if (!$process->isSuccessful()) {
            throw new \RuntimeException($process->getErrorOutput());
        }

        if ($username != $web_user && 'root' != $username) {
            $this->write(" <error>[NO]</error>\n");
            $this->write(
                "\n<comment>Your are <info>$username</info>.\nPlease, use sudo to be <info>{$web_user}</info></comment>.\n\n"
            );
        } else {
            $this->write(" <info>[YES]</info>\n");
        }

        $repositories_path  = $this->getParameter("repositories_path");
        $gitolite_path      = $repositories_path . "/gitolite-admin";
        $gitolite_conf_path = $gitolite_path . "/conf/gitolite.conf";
        $key_path           = $gitolite_path . '/keydir';

        $config_generator = $this->get('jmoati_gitolite_console.config_generator');
        $config_generator->generateRepositoryFile($gitolite_conf_path);
        $config_generator->generateKeysFiles($key_path, true);

        $git_client     = new Client();
        $git_repository = $git_client->getRepository($gitolite_path);
        $git_repository->addAll();
        $git_repository->commit('Config regenerated by GitoliteAdmin');
        $git_repository->push();

    }

}
