jmoati_gitolite_front_homepage:
    pattern:  /
    defaults: { _controller: JmoatiGitoliteFrontBundle:Index:index }

jmoati_gitolite_front_key:
    resource: "@JmoatiGitoliteFrontBundle/Resources/config/routing/key.yml"
    prefix:   /

jmoati_gitolite_front_repository:
    resource: "@JmoatiGitoliteFrontBundle/Resources/config/routing/repository.yml"
    prefix:   /
